@echo off
echo Setting up git...
git remote remove origin 2>nul
git remote add origin "https://github.com/CodAureo-DevStudio/Projetos_codaureo"
echo Adding files...
git add .
echo Committing...
git commit -m "Commit automático de todos os projetos - %date% %time%"
echo Pushing...
git branch -M main
git push -u origin main
echo Done.
